version: '3.9'

services:
  db:
    image: postgres:15
    container_name: ezlink_db
    environment:
      POSTGRES_USER: ezlink_user
      POSTGRES_PASSWORD: ezlink123
      POSTGRES_DB: ezlink_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  web:
    build: .
    container_name: ezlink_web
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://ezlink_user:ezlink123@db:5432/ezlink_db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data: